apiVersion: v1
kind: ConfigMap
metadata:
  name: ecomm-config-w08e1
data:
  # Database Names
  PRODUCTS_DB_NAME: products
  ORDERS_DB_NAME: orders

  # Database Hosts
  ORDER_DB_HOST: order-db-service-w08e1
  ORDER_DB_PORT: "5432"
  PRODUCT_DB_HOST: product-db-service-w08e1
  PRODUCT_DB_PORT: "5432"

  # Database credentials (if your DBs use these defaults)
  ORDER_DB_USER: postgres
  ORDER_DB_PASSWORD: postgres
  PRODUCT_DB_USER: postgres
  PRODUCT_DB_PASSWORD: postgres

