# .github/workflows/cd.yml
name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Azure using service principal stored in GitHub secrets
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Set AKS context
      - name: Set AKS context
        run: |
          az aks get-credentials --resource-group deakin04 --name sit722week08 --overwrite-existing
          kubectl config current-context

      # Ensure ACR login (so AKS can pull images)
      - name: Login to ACR
        run: az acr login --name purvaweek08

      # Deploy Kubernetes manifests
      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/
          kubectl rollout status deployment/frontend
          kubectl rollout status deployment/order-service
          kubectl rollout status deployment/product-service

      # Optional: Verify services
      - name: Get services
        run: kubectl get svc
